# Generated by Django 2.0.3 on 2019-11-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_auto_20191114_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created_at',
        ),
    ]
