# Generated by Django 2.0.3 on 2019-11-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_auto_20191114_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
