# Generated by Django 2.0.3 on 2019-11-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_auto_20191116_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
