# Generated by Django 2.0.3 on 2019-11-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_auto_20191116_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
