# Generated by Django 2.0.3 on 2019-11-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_auto_20191116_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
    ]
